### ISSUE TITLE
Stolen?

### ISSUE THREAD

**Issue by LinkCraftPE** [ItzBulkDev/RPE-Spleef#1]
Why did you take PEMapModder's plugin and put RPE?

**Comment by rj0495** [comment]
It's an OpenSource public plugin so we did that.

**Comment by KyleTheHack3r** [comment]
This is inactive. And as @rj0495 said it's open source. On an unrelated matter, you have done the same to me in the past.

**Comment by LinkCraftPE** [comment]
Kys kyle remember when you stole SoupPvP from xFlare!

**Comment by KyleTheHack3r** [comment]
Rember when I posted proof that Sean told me to improve it?

Also the core plugin was taken from LegionPE-Delta, which PEMapModder has confirmed to be inactive.
